import Providers from "@/providers";
import "@/styles/globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="icon"
          type="image/svg"
          sizes="32x32"
          href="/public/openai-logo.svg"
        />
      </Head>
      <Providers session={session}>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
